development:
  adapter: postgresql
  encoding: unicode
  database: dropquit_dev
  pool: 5
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: dropquit_test
  pool: 5
  host: localhost
