development:
  adapter: postgresql
  encoding: unicode
  database: payvalet_dev
  pool: 5
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: payvalet_test
  pool: 5
  host: localhost
